menu:
  - key: "t"
    desc: Terminal
    cmd: kitty
  - key: "s"
    desc: Browser
    cmd: firefox
  - key: "m"
    desc: Mails
    cmd: thunderbird
  - key: "f"
    desc: File Explorer
    cmd: kitty lf
  - key: "v"
    desc: Vim
    cmd: kitty nvim
  - key: "e"
    desc: Emacs
    cmd: emacs
  - key: "o"
    desc: Quick Open
    # NOTE: Depending on the terminal emulator and it's settings, the become(nohup ...) approach here might not close the terminal appropriately.
    cmd: kitty sh -c "fd --search-path ~ --search-path ~/.config --follow --no-ignore-vcs --format '{}' | fzf --scheme=path --preview='fzf-preview {}' --bind 'enter:become(nohup setsid -f mimeopen -n {} > /dev/null)' --bind 'ctrl-e:become($EDITOR {})' --bind 'ctrl-o:become(lf {})'"
  - key: "c"
    desc: Calculator
    cmd: kitty python3 -i ~/.config/python/pycalc.py
  - key: "u"
    desc: Unicode picker
    cmd: rofimoji -f ~/.config/rofi/math-reduced.csv
  - key: "b"
    desc: System Monitor
    cmd: kitty btop
  - key: "p"
    desc: Sound Mixer
    cmd: kitty wiremix
