# === Options ===

# Setup Terminal
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",st-256color:Tc"

# Set Title of the X Terminal Window, to match the title of the active tmux pane (which is set by the current shell)
# Passes the title "trough"
set -g set-titles on
set -g set-titles-string "#T"
# Automatically sets the windows NAME (not the panes title) to currently running command (unless specified otherwise)
set -g automatic-rename on
# set -g allow-rename on
#  More frequent status line updates
set -g status-interval 0

set -sg escape-time 0

# Starts Index numbers with 1, instead of 0 (Can be reached better from the keyboard)
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# Don't start a login shell
set -g default-command "${SHELL}"

# === Keybindings ===
# Enable Mouse
set-option -g mouse on

# Vim like splits
bind s split-window -v
bind v split-window -h
bind q kill-pane

# Better pane movement
bind -n M-down select-pane -D
bind -n M-left select-pane -L
bind -n M-right select-pane -R
bind -n M-up select-pane -U

# === Styling ===
set -g status-style bg=terminal,fg=white
# set -g status-fg white
set -g status-right ""
set -g status-justify centre
set -g window-status-current-format "#[fg=magenta]#[fg=black]#[bg=magenta]#I #[bg=brightblack]#[fg=white] #W#[fg=brightblack]#[bg=terminal]"
set -g window-status-format "#[fg=yellow]#[fg=black]#[bg=yellow]#I #[bg=brightblack]#[fg=white] #W#[fg=brightblack]#[bg=terminal]"
set -g window-status-separator "  "

# set -g pane-border-status bottom
# set -g pane-border-style bg=colour0,fg=colour0
set -g pane-border-style bg=terminal,fg=colour0
# set -g pane-active-border-style bg=colour8,fg=colour8
set -g pane-active-border-style bg=terminal,fg=colour8,bold

# Hide Status Bar, when there is only one window
# if -F "#{==:#{session_windows},1}" "set -g status off" "set -g status on"
set-hook -g -a window-linked 'if -F "#{==:#{session_windows},1}" "set status off" "set status on"'
set-hook -g -a window-unlinked 'if -F "#{==:#{session_windows},1}" "set status off" "set status on"'

# === Plugins ===
# set -g @mighty-scroll-by-line 'lf fzf'
# set -g @mighty-scroll-fallback-mode 'by-line'
# set -g @mighty-scroll-select-pane on
# set -g @mighty-scroll-interval 1
# run '~/.config/tmux/tmux-mighty-scroll/mighty-scroll.tmux'

set -g @scroll-without-changing-pane 'off'
set -g @scroll-in-moused-over-pane 'on'
set -g @scroll-speed-num-lines-per-scroll 1
set -g @emulate-scroll-for-no-mouse-alternate-buffer on
run-shell ~/.config/tmux/tmux-better-mouse-mode/scroll_copy_mode.tmux

