#!/bin/sh

function testNode() {
	NAME=$(bspc query -T -n $1 | jq -r .client.className)
	if [[ "$NAME" = "Emacs" ]]; then
		sleep 0.5
		bspc node $1 --state tiled
		bspc node $1 -f
	fi
}

bspc subscribe node_add | while read line; do testNode $(echo $line | cut -d " " -f 5); done

