#! /bin/sh

# :!bspc wm -r

# Kill any old querys and subscribtions
killall bspc

if [ "$1" -eq 0 ]; then
	# === INITIAL SETUP ===
	bspc monitor -d 1 2 3 4 5 6 7 8 9
fi
# Setup Desktops for multiple monitors
bspwm_monitor_setup

bspc config border_width         2
bspc config window_gap           6

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true

bspc config pointer_action2 none

# bspc config border_radius 10 &>/dev/null

bspwm_emacs_tiling &

bspc config external_rules_command ~/.config/bspwm/external_rules.sh

bspc wm --adopt-orphans

bspwm_swallow &

# Remove Monocle Layout, when desktop is empty
bspc subscribe desktop_focus | while read line; do
	d=$(echo $line | cut -d " " -f 3)
	[ "$(bspc query -N -d "$d" | wc -l)" -eq 0 ] && bspc desktop "$d" -l tiled
done &

