#!/bin/bash

# Log everything thats happening
exec &> ~/.cache/xinitrc.log

# Set Keyboard Layout and change some annyoing keys
# NOTE: This is currently also done using a global custom mapping, because udev likes to reset the layout on updates.
# See also: https://bugs.archlinux.org/task/77789
# Also see the relevant files: /etc/X11/xorg.conf.d/00-keyboard.conf and /usr/share/X11/xkb/symbols/custom
# If this bug is fixed, both of these files can be deleted again and the layout can be changed from custom to de.
setxkbmap de
# setxkbmap custom
xmodmap -e 'keysym Caps_Lock = Shift_L' # Caps Lock to shift
# xmodmap -e 'keysym dead_circumflex = asciicircum degree' # Only one tap needed for circumflex
xmodmap -e 'keycode 49 = asciicircum degree' # The above line is bugged and also changes 'ä', for some reason?
xmodmap -e 'keysym dead_acute = grave acute' # Change Grave order

xsetroot -name ""
xsetroot -cursor_name left_ptr
xrdb ~/.Xresources
setup_monitor --nobg &
# srandrd -n setup_monitor &
setbg --random ~/wallpapers/ &

# Lockscreen
xss-lock -- ~/.config/X11/xlock.sh &

# Hotkeys
sxhkd &
echo ~/.config/sxhkd/sxhkdrc | entr -nps "pkill -USR1 -x sxhkd; notify-send \"SXHKD reloaded\" -u low" &
playerctld daemon &

# Notifications
# TODO: Update config
dunst &
# ls ~/.config/dunst/dunstrc | entr -nps "killall dunst; dunst & sleep .5; notify-send \"Dunst reloaded\" -u low" &
batsignal -b -w 30 -c 15 -d 5 -D "systemctl hibernate" &

# Automount
# TODO: Is this still necessary?
[[ -e "/dev/sda" ]] && [[ ! -e "/dev/sda1" ]] && udisksctl power-off -b /dev/sda
udiskie -s &

# Compositor
picom &

# Start Gnome Polkit for later authentication (needed by systemctl for example)
# /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Autostart applications
dex -a -e Awesome --term alacritty

# Start WM
awesome

# Cleanup
killall sxhkd entr playerctld nwg-drawer dunst batsignal udiskie srandrd xss-lock picom
# polybar bspc bspwm_swallow bspwm_albert_focus

