#!/usr/bin/env bash

# Log everything thats happening
exec &> ~/.cache/xinitrc.log

# Set Keyboard Layout and change some annyoing keys
setxkbmap de
xmodmap -e 'keysym Caps_Lock = Shift_L' # Caps Lock to shift
# xmodmap -e 'keysym dead_circumflex = asciicircum degree' # Only one tap needed for circumflex
xmodmap -e 'keycode 49 = asciicircum degree' # The above line is bugged and also changes 'ä', for some reason?
xmodmap -e 'keysym dead_acute = grave acute' # Change Grave order

xrdb ~/.Xresources
srandrd -n -e xrandr --output HDMI-1 --right-of eDP-1 --auto &
setwallpaper &

# Lockscreen
xss-lock -- ~/.config/X11/xlock.sh &

# Hotkeys
sxhkd &
echo ~/.config/sxhkd/sxhkdrc | entr -nps "pkill -USR1 -x sxhkd; notify-send \"SXHKD reloaded\" -u low" &
playerctld &

# Notifications
dunst &
# echo ~/.config/dunst/dunstrc | entr -nps "pkill dunst; dunst & sleep .5; notify-send \"Dunst reloaded\" -u low" &
batsignal -w 30 -c 15 -d 5 -D "systemctl hibernate" &

# Setup Automount
# Disable SD card reader, that remains active for some reason
[[ -e "/dev/sda" ]] && [[ ! -e "/dev/sda1" ]] && udisksctl power-off -b /dev/sda
udiskie &

# Compositor
picom &

# Autostart applications
dex -a -e Awesome --term kitty

# Start WM
exec awesome
