#!/bin/bash

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# === CONFIG ===

hc set auto_detect_monitors true
hc set default_frame_layout grid
hc set_layout grid
hc set mouse_recenter_gap 10000
hc set focus_follows_mouse true
hc set update_dragged_clients true
hc set tree_style '╾│ ├└╼─┐'

hc set focus_crosses_monitor_boundaries true # Focus commands work acrous monitors
hc set focus_stealing_prevention false

# Frame Theming
hc set frame_gap 6
# Border of Frames
hc set frame_border_width 4
hc set frame_border_active_color '#345F0C'
hc set frame_active_opacity 50
hc set frame_border_normal_color '#565656'
hc set frame_normal_opacity 25
# Remove border, when only one frame, but otherwise show all borders
hc set smart_frame_surroundings true
hc set always_show_frame true
# Disable Frame Background
hc set frame_bg_normal_color '#00000000'
hc set frame_bg_active_color '#00000000'

# Window Decorations
hc set window_gap 6
# hc set smart_window_surroundings true

# === THEMING ===

hc attr theme.reset 1

# Window Borders
hc attr theme.border_width 2
hc attr theme.active.color '#93ae7cdd'
hc attr theme.normal.color '#81a1c1ef'
hc attr theme.urgent.color '#7811A1dd'
hc attr theme.background_color '#111111'



# === KEYBINDINGS ===

# remove all existing keybindings
hc keyunbind --all

hc keybind Super-c close_and_remove

# basic movement in tiling and floating mode
# focusing clients
hc keybind Super-Left  focus left
hc keybind Super-Down  focus down
hc keybind Super-Up    focus up
hc keybind Super-Right focus right
hc keybind Super-n     cycle +1
hc keybind Super-Shift-n cycle -1

# moving clients in tiling and floating mode
hc keybind Super-Shift-Left  shift left
hc keybind Super-Shift-Down  shift down
hc keybind Super-Shift-Up    shift up
hc keybind Super-Shift-Right shift right

# splitting frames
hc keybind Super-s chain , split bottom 0.5 , focus -e down
hc keybind Super-v chain , split right 0.5 , focus -e right
# let the current frame explode into subframes
# hc keybind Super-Control-space split explode
# Remove Frame and merge it
# hc keybind Super-BackSpace remove

# resizing frames and floating clients
resizestep=0.02
hc keybind Super-Control-Left    resize left +$resizestep
hc keybind Super-Control-Down    resize down +$resizestep
hc keybind Super-Control-Up      resize up +$resizestep
hc keybind Super-Control-Right   resize right +$resizestep

# toggle floating
hc keybind Super-Shift-f set_attr clients.focus.floating toggle
# Cycle through layouts
hc keybind Super-Shift-space cycle_layout +1 grid max

# tags
tag_names=( {1..9} )

# Setup Tag Keybindings
for i in "${tag_names[@]}" ; do
    hc add "$i"
    hc keybind "Super-$i" use "$i"
    hc keybind "Super-Shift-$i" move "$i"
done
hc keybind Super-Tab use_previous
# Remove default tag
hc use 1
hc merge_tag default


# mouse
hc mouseunbind --all
hc mousebind Super-Button1 move
hc mousebind Super-Button2 zoom
hc mousebind Super-Button3 resize



# === RULES ===

hc unrule -F
hc rule focus=on hook=newclient # focus new clients
hc rule class='dmenu' floating=on
hc rule title='zoom' floating=on floatplacement=none
hc rule class='zoom' floating=on floatplacement=none
# hc rule class='zoom' title~'Zoom - .*' floating=false
hc rule class='zoom' title='Zoom Meeting' floating=false
hc rule class~'Minecraft*' floating=on
hc rule class='albert' floating=on focus=on floatplacement=center hook=albertfocus
hc rule class='Nwg-drawer' floating=on focus=on floatplacement=center fullscreen=on
hc rule class='Nwg-bar' floating=on focus=on floatplacement=center manage=off
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off



# === External Scripts ===
pgrep -fc "mouse_follows_focus.sh" || ~/.config/herbstluftwm/mouse_follows_focus.sh &
pgrep -fc "albertfocus.sh" || ~/.config/herbstluftwm/albertfocus.sh &
pgrep -fc "fixed_size_window.sh" || ~/.config/herbstluftwm/fixed_size_window.sh &

# === FINAL SETUP ===

# unlock, just to be sure
hc unlock

# multi monitor setup
hc detect_monitors

