# === Opacity ===
active-opacity = 1;
# inactive-opacity = 0.9;
inactive-opacity = 1;

opacity-rule = [
	"30:class_g = 'Bspwm'"
]

focus-exclude = [
	# "class_g = 'dwm'",
	# "class_g = 'dmenu'",
	# To use built in Opacity
	"class_g = 'st-256color'",
	"class_g = 'i3lock'"
]

# === Shadows ===
shadow = true;
shadow-radius = 6;
shadow-offset-x = 0;
shadow-offset-y = 0;
shadow-opacity = 0.85;
xinerama-shadow-crop = true;
shadow-exclude = [
	"class_g = 'Polybar'",
	"class_g = 'firefox' && argb",
	"class_g = 'Thunderbird' && argb",
	"class_g = 'zoom' && argb",
	"class_g = 'Bspwm'",
	"class_g = 'albert'",
	"name = 'cpt_frame_window'"
]

# === Fading ===
fading = true;
fade-delta = 5;
fade-in-step = 0.03;
fade-out-step = 0.03;

# === Rounded Corners ===
# corner-radius = 15.0;
# round-borders = 1;
rounded-corners-exclude = [
  #"window_type = 'normal'",
  "class_g = 'awesome'",
  "class_g = 'URxvt'",
  "class_g = 'XTerm'",
  "class_g = 'kitty'",
  "class_g = 'Alacritty'",
  "class_g = 'Polybar'",
  "class_g = 'code-oss'",
  #"class_g = 'TelegramDesktop'",
  "class_g = 'firefox'",
  "class_g = 'Thunderbird'"
];
round-borders-exclude = [
  #"class_g = 'TelegramDesktop'",
];

# === Animations ===
transition-length = 300;
transition-pow-y = 0.3;
transition-pow-x = 0.3;
transition-pow-w = 0.3;
transition-pow-h = 0.3;
size-transition = true;

# === Custom Wintypes ===
wintypes: {
	popup_menu = { opacity = 0.95 };
	dropdown_menu = { opacity = 0.95 };
	dnd = { shadow = false }
}

# === Other ===
# experimental-backends = true

