;; This file is generated by Emacs.org. Make changes there.

(defun list-faces (pos)
  "Get the font faces at POS."
  (interactive "d")
  (message "All Faces: %s" (remq nil
                                 (list
                                  (get-char-property pos 'read-face-name)
                                  (get-char-property pos 'face)
                                  (plist-get (text-properties-at pos) 'face)))))

(defun curr-line-empty-p ()
  "Return non-nil, if the current line is empty."
  (pcase (thing-at-point 'line t)
    ("" 't)
    ("\n" 't)))

(setq read-process-output-max (* 1024 1024)) ;; 1mb
(setq gc-cons-threshold 100000000) ;; 100mb
(setq lsp-idle-delay 0.5) ;; Default
(setq lsp-log-io nil) ;; Default

(defun fab/display-startup-time ()
  (message "Emacs startup finished: took %s; %d features loaded; with %d garbage collections"
           (format "%.2f seconds"
                   (float-time
                   (time-subtract after-init-time before-init-time)))
           (length features)
           gcs-done))

(add-hook 'emacs-startup-hook #'fab/display-startup-time)

(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)
(tooltip-mode -1)
(set-fringe-mode 10) ;; Left and Right Border
(when (member 'doom-oceanic-next (custom-available-themes))
  ;; (load-theme 'doom-gruvbox 't)
  (load-theme 'doom-oceanic-next 't))
(setq inhibit-startup-message t)
;; (setq visible-bell t)

(setq frame-title-format '(multiple-frames "%b"
                                           ("" "%b - Emacs")))
;; (set-frame-parameter (selected-frame) 'alpha '(90 . 90))
;; (add-to-list 'default-frame-alist '(alpha . (90 . 90)))

;; (set-fontset-font "fontset-default" nil "MesloLGS NF")
(set-face-attribute 'default nil :font "FiraCode Nerd Font:style=Retina" :height 120)
(set-face-attribute 'fixed-pitch nil :font "FiraCode Nerd Font:style=Retina")
(set-face-attribute 'variable-pitch nil :font "FreeSans" :height 120 :weight 'normal)

(show-paren-mode)

(global-hl-line-mode)

;; Set the line number explicitly, to avoid it being reset to variable-pitch by org mode
(set-face-attribute 'line-number nil :inherit 'fixed-pitch)
(set-face-attribute 'line-number-current-line nil :background 'unspecified :inherit '(hl-line line-number))

(setq display-line-numbers-type 'relative)
(global-display-line-numbers-mode 1)
;; We don't need the line number in the modeline anymore
(line-number-mode -1)
;; (column-number-mode)
(setq-default indicate-buffer-boundaries 't)


;; cleaner scratch buffer
(setq initial-major-mode 'fundamental-mode)
(setq initial-scratch-message nil)

(dolist (mode '(term-mode-hook
                vterm-mode-hook
                eshell-mode-hook
                shell-mode-hook
                help-mode-hook
                helpful-mode-hook
                Info-mode-hook
                apropos-mode-hook
                xref-after-update-hook
                ivy-occur-mode-hook
                ivy-occur-grep-mode-hook
                imenu-list-major-mode-hook
                treemacs-mode-hook
                pdf-view-mode-hook))
  (add-hook mode (lambda () (display-line-numbers-mode 0))))

(dolist (mode '(term-mode-hook
                vterm-mode-hook
                eshell-mode-hook
                shell-mode-hook))
  (add-hook mode (lambda () (setq-local global-hl-line-mode nil))))

(setq mouse-wheel-scroll-amount '(3))
(setq mouse-wheel-flip-direction 't)
(setq mouse-wheel-progressive-speed nil)
(setq scroll-step 5)

(require 'package)

(setq package-archives '(("melpa" . "https://melpa.org/packages/")
                         ("org" . "https://orgmode.org/elpa/")
                         ("elpa" . "https://elpa.gnu.org/packages/")))

(package-initialize)
(unless package-archive-contents
  (package-refresh-contents))
(unless (package-installed-p 'use-package)
  (package-install 'use-package))

(require 'use-package)
(setq use-package-always-ensure t)
(setq use-package-verbose t)
(setq use-package-compute-statistics t)

(use-package auto-package-update
  :init
  (setq auto-package-update-last-update-day-filename "var/last-package-update-day")
  :config
  (setq auto-package-update-interval 14)
  (setq auto-package-update-delete-old-versions t)
  (setq auto-package-update-prompt-before-update t)
  ;; (setq auto-package-update-hide-results t)
  (auto-package-update-maybe))

(global-auto-revert-mode)

(electric-pair-mode)
(setq electric-pair-open-newline-between-pairs 't)

(setq warning-suppress-log-types '((comp)))

;; Silence compiler warnings as they can be pretty disruptive
(setq comp-async-report-warnings-errors nil)

;; (setq-default tab-width 2)
;; (setq-default evil-shift-width tab-width)

;; Don't use Tabs
;; (setq-default indent-tabs-mode nil)

(setq tab-always-indent nil)

(use-package electric-operator
  :hook ((prog-mode . electric-operator-mode)
         (emacs-lisp-mode . (lambda () (electric-operator-mode -1))))
  )

(use-package treemacs
  :config
  (treemacs-project-follow-mode)
  (setq treemacs--project-follow-delay 0)
  (define-key treemacs-mode-map [mouse-1] #'treemacs-single-click-expand-action)
  (treemacs-fringe-indicator-mode 0)
  (treemacs-indent-guide-mode))
;; (use-package treemacs-evil
;;   :after treemacs)

(use-package no-littering)

(require 'recentf)
(add-to-list 'recentf-exclude no-littering-var-directory)
(add-to-list 'recentf-exclude no-littering-etc-directory)

;; Change location of auto-save and backup files
(setq backup-directory-alist `(("." . ,(no-littering-expand-var-file-name "backups/"))))
(setq auto-save-file-name-transforms
        `((".*" ,(no-littering-expand-var-file-name "auto-save/") t)))

;; Keep init.el clean of custom variables
(setq custom-file (no-littering-expand-etc-file-name "custom.el"))
(load custom-file)

(recentf-mode 1)
(setq recentf-max-saved-items 100)
(setq recentf-max-menu-items recentf-max-saved-items)

(use-package project
  :init
  ;; Ignore Helpful Mode buffers
  (setq project-ignore-buffer-conditions '((major-mode . helpful-mode)))
  (setq project-kill-buffer-conditions ;; Copied from original, with slight modification for helpful mode buffers
        '(buffer-file-name
          (and
           (major-mode . fundamental-mode)
           "\\`[^ ]")
          (and
           (derived-mode . special-mode)
           (not
            (major-mode . help-mode))
           (not
            (major-mode . helpful-mode))
           (not
            (derived-mode . gnus-mode)))
          (derived-mode . compilation-mode)
          (derived-mode . dired-mode)
          (derived-mode . diff-mode)
          (derived-mode . comint-mode)
          (derived-mode . eshell-mode)
          (derived-mode . change-log-mode)))
  (setq project-kill-buffers-display-buffer-list t)
  )

(global-set-key (kbd "<escape>") 'keyboard-escape-quit)
(global-set-key (kbd "C-:") 'eval-expression)

(setq evil-emacs-state-cursor '("red" box))
(setq evil-normal-state-cursor '("green" box))
(setq evil-visual-state-cursor '("orange" box))
(setq evil-insert-state-cursor '("lightblue" bar))
(setq evil-replace-state-cursor '("red" hollow))
(setq evil-operator-state-cursor '("red" hbar))
(setq evil-motion-state-cursor '("orange" hbar))

;; (setq evil-want-C-w-in-emacs-state 't)
(setq evil-want-Y-yank-to-eol 't)
(setq evil-want-C-u-scroll 't)
(setq evil-want-C-i-jump nil)
;; (setq evil-respect-visual-line-mode 't)
(setq evil-split-window-below 't)
(setq evil-vsplit-window-right 't)
(setq evil-undo-system 'undo-redo)
(setq evil-kill-on-visual-paste nil)
(setq evil-echo-state nil)
(setq evil-want-keybinding nil)
(setq evil-want-integration 't)

;; Start with forward searches by default (important for Swiper)
(setq isearch-forward 't)
;; (setq evil-search-module 'evil-search)

(use-package evil)
(evil-mode 1)
;; (add-to-list 'evil-insert-state-modes 'vterm-mode)
(define-key evil-insert-state-map (kbd "C-g") 'evil-normal-state)
(evil-define-operator fab/evil-delete-char-noyank (beg end type register)
  "Delete next character. Don't yank to register."
  :motion evil-forward-char
  (interactive "<R><x>")
  (evil-delete beg end type ?_))
(evil-define-key 'normal 'global "x" 'fab/evil-delete-char-noyank)

(use-package evil-surround
  :after evil
  :config
  (general-def '(normal visual) evil-surround-mode-map
    "s" 'evil-surround-region
    "S" 'evil-Surround-region)
  ;; TODO: Text objects for other common surround stuff
  (global-evil-surround-mode 1))

(use-package evil-collection
  :after evil
  :config
  ;; (delete 'info evil-collection-mode-list)
  (evil-collection-init))

(use-package which-key
  :init
  (setq which-key-idle-delay 0.1) ;; Can cause errors when 0
  (setq which-key-prefix-prefix "")
  ;; (setq which-key-allow-evil-operators 't)
  ;; (setq which-key-show-operator-state-maps 't)
  (which-key-mode))
;; (which-key-setup-side-window-right-bottom)
(global-set-key (kbd "<C-tab>") 'which-key-show-top-level)

(use-package general
  :config
  (general-evil-setup 't)
  (general-create-definer fab/leader-def
    :states '(normal visual)
    :prefix "SPC"))

(general-def 'normal 'override
  "<M-down>"  'evil-window-down
  "<M-left>"  'evil-window-left
  "<M-right>" 'evil-window-right
  "<M-up>"    'evil-window-up
)

(general-def 'normal
  ;; TODO: make only active when not in Read-Only buffer
  ;; [remap evil-ret] '(lambda () (interactive) (evil-open-below 0) (evil-normal-state)) 
  ;; "S-<return>" '(lambda () (interactive) (evil-open-above 0) (evil-normal-state))
  "C-w C-q"   'evil-quit
  "U"         'evil-redo)

(general-def 'insert
  ;; Terminal style paste
  "C-S-V" '(lambda () (interactive) (evil-paste-before 1) (right-char)))

(general-def '(normal insert emacs visual) 'override
  "C-SPC" 'execute-extended-command
  "C-a" 'universal-argument)

(general-def universal-argument-map
  "C-a" 'universal-argument-more)

(fab/leader-def
  "SPC" '(execute-extended-command :wk "Run CMD"))

(fab/leader-def :infix "f"
  ""  '(:ignore t :wk "Files")
  "f" 'find-file
  "e" 'treemacs
  "r" '(counsel-recentf :wk "Recent Files")
  "i" '((lambda () (interactive) (find-file "~/.config/emacs/Emacs.org"))   :wk "Emacs Init")
  "o" '((lambda () (interactive) (find-file "~/Notes/Org_Mode_Basics.org")) :wk "Org Notes"))

(fab/leader-def "p" '(:keymap project-prefix-map :wk "Projects"))

(use-package evil-nerd-commenter
  :general ('(normal visual) "#" 'evilnc-comment-or-uncomment-lines))

(use-package ivy
  :diminish
  :demand t
  :bind (("C-s" . swiper)
         :map ivy-minibuffer-map
         ("TAB" . ivy-alt-done)
         ("C-g" . ivy-beginning-of-buffer)
         ("C-o" . ivy-occur)
         ("C-a" . ivy-dispatching-done)
         ("C-S-a" . ivy-dispatching-call)
         ("C-r" . ivy-restrict-to-matches)
         ("C-p" . yank)
         :map ivy-switch-buffer-map
         ("C-d" . ivy-switch-buffer-kill))
  :config
  (setq ivy-use-selectable-prompt 't)
  (setq ivy-wrap 't)
  ;; Ignore the the order of words
  (setq ivy-re-builders-alist '((t . ivy--regex-ignore-order)))
  ;; Don't show . and .. directories
  (setq ivy-extra-directories '())
  ;; Use Monospace fonts in switch-buffer
  (set-face-attribute 'ivy-org nil  :inherit '(fixed-pitch org-level-4))
  (fab/leader-def ivy-mode-map
    "I" '(ivy-resume :wk "Ivy Resume"))
  (ivy-mode 1))

(use-package all-the-icons-ivy-rich
  :after (ivy counsel)
  :config
  (all-the-icons-ivy-rich-mode 1))

(use-package ivy-rich
  :after (ivy counsel all-the-icons-ivy-rich)
  :config
  (setq ivy-rich-path-style 'abbrev)
  (ivy-rich-mode 1)

  ;; Fix "Not a Directory Error" that appears on Emacs 30 and above, with some buffers.
  ;; Why this bug only appears on newer Emacs versions is not clear to me.
  (advice-add #'helpful--buffer :filter-return
              (lambda (buf)
                (with-current-buffer buf
                  (setq-local list-buffers-directory nil))
                buf))

  (advice-add #'info-setup :after
              (lambda (_ buf)
                (with-current-buffer buf
                  (setq-local list-buffers-directory nil))
                buf))
  )

(use-package counsel
  :after ivy
  ;; :bind (("M-x" . counsel-M-x)
  ;;        ("C-SPC" . counsel-M-x)
  ;;        ("C-x b" . counsel-switch-buffer)
  ;;        ("C-x C-f" . counsel-find-file))
  :config
  (setq ivy-initial-inputs-alist nil)
  (fab/leader-def ivy-mode-map
    "b" '(counsel-switch-buffer :wk "Buffers")
    "P" '(counsel-yank-pop :wk "Paste Kill Ring"))
  (counsel-mode 1))

(use-package prescient
  :init
  (setq prescient-sort-length-enable nil)
  (setq prescient-sort-full-matches-first 't)
  :config
  (prescient-persist-mode 1))

(use-package ivy-prescient
  :after (prescient counsel)
  :init
  ;; Use normal ivy filtering
  (setq ivy-prescient-enable-filtering nil)
  ;; (setq ivy-prescient-retain-classic-highlighting t)
  :config
  (ivy-prescient-mode 1)
  (setq ivy-prescient-sort-commands (append ivy-prescient-sort-commands '(counsel-recentf counsel-org-goto))))

;; Remove useless default actions ("copy" and "insert")
;; (ivy-set-actions 't nil)

(ivy-add-actions
 'counsel-switch-buffer
 '(("s" (lambda (BNAME) (interactive) (evil-window-split) (switch-to-buffer BNAME)) "Split")
   ("v" (lambda (BNAME) (interactive) (evil-window-vsplit) (switch-to-buffer BNAME)) "VSplit")))

(ivy-add-actions
 'counsel-find-file
 '(("s" (lambda (FNAME) (interactive) (evil-window-split nil FNAME)) "Split")
   ("v" (lambda (FNAME) (interactive) (evil-window-vsplit nil FNAME)) "VSplit")))

;; TODO: Open in same window
(use-package helpful
  :init
  (setq helpful-switch-buffer-function #'pop-to-buffer)
  :custom
  (counsel-describe-function-function #'helpful-callable)
  (counsel-describe-variable-function #'helpful-variable)
  (counsel-describe-symbol-function #'helpful-symbol)
  :bind
  ;; ([remap describe-function] . counsel-describe-function)
  ([remap describe-command] . helpful-command) ;; TODO: Needed for what?
  ;; ([remap describe-variable] . counsel-describe-variable)
  ;; ([remap describe-symbol] . counsel-describe-symbol)
  ([remap describe-key] . helpful-key)
  ("C-h p" . helpful-at-point))

(use-package rainbow-delimiters
  :hook (prog-mode . rainbow-delimiters-mode))

(use-package doom-themes
  :config
  ;; Only load theme, if it is not already loaded.
  (unless (member 'doom-oceanic-next custom-enabled-themes)
    ;; (load-theme 'doom-gruvbox 't)
    (load-theme 'doom-oceanic-next 't)))

(use-package all-the-icons)
(use-package doom-modeline
  :init
  (setq mode-line-percent-position nil)
  (doom-modeline-mode 1)
  :custom
  (doom-modeline-height 25)
  (doom-modeline-buffer-file-name-style 'truncate-with-project)
  (doom-modeline-buffer-encoding nil)
  (doom-modeline-indent-info 't)
  (doom-modeline-lsp nil)
  (doom-modeline-env-version nil))

(defun fab/clear-wc-modeline (&rest r)
  (unless wc-mode
    (setq wc-buffer-stats "")))

(use-package wc-mode
  :commands wc-mode
  :config
  (setq mode-line-misc-info (append mode-line-misc-info '(wc-buffer-stats)))
  (setq wc-modeline-format "WC: %tw")
  ;; (add-hook 'wc-mode-hooks 'doom-modeline-redisplay)
  (advice-add 'wc-mode :after 'fab/clear-wc-modeline))

(use-package ligature
  :load-path "~/.config/emacs/ligature.el"
  :config
  (ligature-set-ligatures 'prog-mode '("|||>" "<|||" "<==>" "<!--" "~~>" "***" "||=" "||>"
                                       ":::" "::=" "=:=" "===" "==>" "=!=" "=>>" "=<<" "=/=" "!=="
                                       ">=>" ">>=" ">>>" ">>-" ">->" "->>" "-->" "---" "-<<"
                                       "<~~" "<~>" "<*>" "<||" "<|>" "<$>" "<==" "<=>" "<=<" "<->"
                                       "<--" "<-<" "<<=" "<<-" "<<<" "<+>" "</>" "###" "#_(" "..<"
                                       "..." "+++" "/==" "///" "_|_" "www" "&&" "^=" "~~" "~@" "~="
                                       "~>" "~-" "**" "*>" "*/" "||" "|}" "|]" "|=" "|>" "|-" "{|"
                                       "[|" "]#" "::" ":=" ":>" ":<" "$>" "==" "=>" "!=" "!!" ">:"
                                       ">=" ">>" ">-" "-~" "-|" "->" "--" "-<" "<~" "<*" "<|" "<:"
                                       "<$" "<=" "<>" "<-" "<<" "<+" "</" "#{" "#[" "#:" "#=" "#!"
                                       "##" "#(" "#?" "#_" "%%" ".=" ".-" ".." ".?" "+>" "++" "?:"
                                       "?=" "?." "??" ";;" "/=" "/>" "//" "__" "~~" "://"))
  (global-ligature-mode 't)
  )

;; (use-package yascroll
;;   :config
;;   (set-face-attribute 'yascroll:thumb-fringe nil :foreground "#3c3836" :background "#3c3836")
;;   (global-yascroll-bar-mode 1))

(defun fab/center-text-visual (&optional width)
  (setq visual-fill-column-width (or width 80))
  (setq visual-fill-column-center-text t)
  (visual-fill-column-mode 1))

(use-package visual-fill-column
  :hook ((org-mode     . (lambda () (fab/center-text-visual 90)))
         (helpful-mode . (lambda () (fab/center-text-visual 90)))
         (Info-mode    . (lambda () (fab/center-text-visual 100)))))

(defun fab/company-on-return ()
  "Complete Selection when a value is selected, otherwise insert a newline"
  (interactive)
  (if company-selection
      (company-complete-selection)
    (newline)))

(defun fab/company-on-tab ()
  "Insert current selection or default to the first one."
  (interactive)
  (unless company-selection
    (company-select-first))
  (company-complete-selection))

(use-package company
  :hook ((lsp-mode prog-mode) . company-mode)
  :config
  (general-def  company-mode-map
    "<tab>"     'company-indent-or-complete-common)
  (general-def  company-active-map
    ;; "<tab>"    'company-complete-selection
    ;; "<tab>"    'company-complete
    "<tab>"    'fab/company-on-tab
    "<return>" 'fab/company-on-return
    "<escape>" 'company-abort
    "<down>"   'company-select-next
    "<up>"     'company-select-previous)
  :custom
  (company-minimum-prefix-length 1)
  (company-idle-delay 0.2) ;; Maybe set to 0 or 0.01?
  (company-tooltip-align-annotations 't)
  (company-selection-wrap-around 't)
  )

(use-package company-box
  :after company
  :hook (company-mode . company-box-mode))

(use-package company-prescient
  :after company
  :config
  (company-prescient-mode 1))

(setq posframe-mouse-banish nil)

(defun fab/reshrink-window (&optional window)
  (interactive)
  (balance-windows (window-parent window))
  (shrink-window-if-larger-than-buffer window)
  (if window
      (with-selected-window window
        (shrink-window -1))
    (shrink-window -1)))

(advice-add 'lsp-find-locations :after
            (lambda (&rest r)
              (when (eq (buffer-local-value 'major-mode (window-buffer)) 'xref--xref-buffer-mode)
                (fab/reshrink-window))))

(advice-add 'help-window-setup :after
            (lambda (window &rest r)
              (when (eq (buffer-local-value 'major-mode (window-buffer window)) 'help-mode)
                (fab/reshrink-window window))))

(advice-add 'pop-to-buffer :after
            (lambda (&rest r)
              (when (string-prefix-p "*ivy-occur" (buffer-name))
                (when (eq major-mode 'ivy-occur-grep-mode)
                  (goto-line 1)
                  (ivy-occur-delete-candidate)
                  (ivy-occur-delete-candidate)
                  (ivy-occur-delete-candidate))
                (fab/reshrink-window))))

(use-package imenu-list
  :config
  ;; (fab/leader-def "O" 'imenu-list-smart-toggle)
  (setq imenu-list-focus-after-activation t)
  (setq imenu-list-position 'left)
  (setq imenu-list-size 30)
  (setq imenu-list-mode-line-format mode-line-format))

(use-package dashboard
  :config
  (setq dashboard-items '((projects . 5)
                          (recents . 5)
                          (bookmarks . 5)))
  (setq dashboard-set-heading-icons t)
  (setq dashboard-set-file-icons t)
  (setq dashboard-set-navigator t)
  (setq dashboard-center-content t)
  (setq dashboard-startup-banner "~/.local/share/icons/emacs_medium.png")
  (setq dashboard-projects-backend 'project-el)
  (dashboard-setup-startup-hook))

;; Seems to be required by some other packages
(use-package monitor)

(defun fab/org-mode-setup ()
  (setq tab-width 2)
  (variable-pitch-mode 1)
  (display-line-numbers-mode 0)
  (visual-line-mode 1)
  (electric-pair-local-mode -1))

(defun fab/org-font-setup ()
  ;; Replace list hyphen with dot
  ;; (font-lock-add-keywords 'org-mode
  ;;                         '(("^ *\\([-]\\) "
  ;;                            (0 (prog1 () (compose-region (match-beginning 1) (match-end 1) "•"))))))

  ;; Set faces for heading levels
  (dolist (face '((org-level-1 . 2.0)
                  (org-level-2 . 1.5)
                  (org-level-3 . 1.25)
                  (org-level-4 . 1.15)
                  (org-level-5 . 1.05)
                  (org-level-6 . 1.0)
                  (org-level-7 . 1.0)
                  (org-level-8 . 1.0)))
    (set-face-attribute (car face) nil :font "FreeSans" :weight 'regular :height (cdr face)))

  (require 'org-indent)
  (set-face-attribute 'org-document-title nil :font "FreeSans" :weight 'bold :height 3.0)

  ;; Ensure that anything that should be fixed-pitch in Org files appears that way
  (set-face-attribute 'org-block nil    :inherit 'fixed-pitch)
  (set-face-attribute 'org-block-begin-line nil :inherit 'fixed-pitch)
  (set-face-attribute 'org-checkbox nil  :inherit 'fixed-pitch)
  ;; (set-face-attribute 'org-code nil     :inherit '(shadow fixed-pitch))
  (set-face-attribute 'org-code nil     :inherit 'fixed-pitch)
  (set-face-attribute 'org-formula nil  :inherit 'fixed-pitch)
  (set-face-attribute 'org-latex-and-related nil  :inherit 'fixed-pitch)
  (set-face-attribute 'org-hide   nil   :inherit 'fixed-pitch)
  ;; (set-face-attribute 'org-indent nil   :inherit '(org-hide fixed-pitch))
  (set-face-attribute 'org-meta-line nil :foreground 'unspecified :inherit '(font-lock-comment-face fixed-pitch))
  (set-face-attribute 'org-drawer   nil   :inherit 'fixed-pitch)
  (set-face-attribute 'org-document-info-keyword nil :inherit '(shadow fixed-pitch))
  (set-face-attribute 'org-special-keyword nil :inherit '(font-lock-keyword-face fixed-pitch))
  (set-face-attribute 'org-table nil    :inherit 'fixed-pitch)
  ;; (set-face-attribute 'org-verbatim nil :inherit '(shadow fixed-pitch)))
  (set-face-attribute 'org-verbatim nil :inherit 'fixed-pitch))

(use-package org
  :pin org ;; Use Org-Mode Archive
  :hook (org-mode . fab/org-mode-setup)
  :config
  (setq org-ellipsis " ▾")
  (setq org-hide-emphasis-markers 't)
  (setq org-pretty-entities 't)
  (setq org-startup-with-latex-preview 't)
  (setq org-cycle-global-at-bob 't)
  ;; (setq org-startup-folded 't)
  (setq org-catch-invisible-edits 'smart)
  (setq org-M-RET-may-split-line nil)
  (setq org-fontify-quote-and-verse-blocks t)
  (setq org-highlight-latex-and-related '(latex))
  (setq org-list-indent-offset 1)
  (setq org-hide-leading-stars 't)
  (setq org-hidden-keywords '(title subtitle author email date))
  (setq org-indent-indentation-per-level 2)
  (setq org-startup-indented 't)
  (setq org-edit-src-content-indentation 2)
  (setq org-format-latex-options (plist-put org-format-latex-options :scale 1.25))
  (setq org-preview-latex-image-directory (no-littering-expand-var-file-name "ltximg/"))
  (setq org-image-actual-width 600)
  (require 'org-tempo)
  (add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
  (add-to-list 'org-structure-template-alist '("py" . "src python"))
  (fab/org-font-setup))

(defun org-table-insert-column-after ()
  "Insert a new column into the table, after the current coloumn"
  (interactive)
  (unless (org-at-table-p) (user-error "Not at a table"))
  (when (eobp) (save-excursion (insert "\n")))
  (unless (string-match-p "|[ \t]*$" (org-current-line-string))
    (org-table-align))
  (org-table-find-dataline)
  (let ((col (1+ (max 1 (org-table-current-column))))
        (beg (org-table-begin))
        (end (copy-marker (org-table-end)))
        (shrunk-columns (org-table--list-shrunk-columns)))
    (org-table-expand beg end)
    (save-excursion
      (goto-char beg)
      (while (< (point) end)
        (unless (org-at-table-hline-p)
          (org-table-goto-column col t)
          (insert "|"))
        (forward-line)))
    (org-table-goto-column col)
    (org-table-align)
    ;; Shift appropriately stored shrunk column numbers, then hide the
    ;; columns again.
    (org-table--shrink-columns (mapcar (lambda (c) (if (< c col) c (1+ c)))
                                       shrunk-columns)
                               beg end)
    (set-marker end nil)
    ;; Fix TBLFM formulas, if desirable.
    (when (or (not org-table-fix-formulas-confirm)
              (funcall org-table-fix-formulas-confirm "Fix formulas? "))
      (org-table-fix-formulas "$" nil (1- col) 1))))

(use-package org-superstar
  :after org
  :hook (org-mode . org-superstar-mode)
  :custom
  (org-superstar-headline-bullets-list '("◉" "◎" "●" "⊙" "○" "●" "◈" "◇"))
  ;; (org-superstar-remove-leading-stars 't)
  (org-superstar-item-bullet-alist '((?* . ?◆) (?+ . ?○) (?- . ?●)))
  :config
  (set-face-attribute 'org-superstar-item nil :height 0.5) 
  ;; :custom-face
  ;; (org-superstar-header-bullet ((t (:inherit 'fixed-pitch))))
  ;; (org-superstar-item ((t (:inherit 'fixed-pitch))))
  )

(use-package org-appear
  ;; :load-path "~/.config/emacs/org-appear"
  :after org
  :init
  (setq org-appear-autolinks 't
        org-appear-autoentities 't
        org-appear-autosubmarkers 't
        org-appear-autokeywords 't
        org-appear-inside-latex 't)
  :hook (org-mode . org-appear-mode))

(use-package org-fragtog
  :after org
  :hook (org-mode . org-fragtog-mode))

(use-package org-pretty-table
  :load-path "~/.config/emacs/org-pretty-table"
  :after org)
  ;; :hook (org-mode . org-pretty-table-mode))

(define-minor-mode org-sidebar-outline-mode
  "A minor mode for the sidebar, intended for the outline."
  :keymap `(("q" . delete-window)
            (,(kbd "RET") . fab/jump-to-point-and-show)
            (,(kbd "<mouse-1>") . fab/jump-to-point-and-show))
  :interactive nil)
(evil-make-overriding-map org-sidebar-outline-mode-map)
(evil-collection-inhibit-insert-state 'org-sidebar-outline-mode-map)

(defun fab/open-tree-view ()
  "Open a clone of the current buffer to the left, resize it to 30 columns, and bind <mouse-1> to jump to the same position in the base buffer."
  (interactive)
  (let ((new-buffer-name (concat "<tree>" (buffer-name))))
    (cond ((get-buffer-window new-buffer-name)
           ;; (select-window (get-buffer-window new-buffer-name)))
           (delete-window (get-buffer-window new-buffer-name)))
          ((get-buffer new-buffer-name) ;; Use existing tree buffer
           (split-window-right 30)
           (switch-to-buffer new-buffer-name))
          ('t ;; Create tree buffer
           (split-window-right 30)
           (clone-indirect-buffer new-buffer-name nil t)
           (switch-to-buffer new-buffer-name)
           (read-only-mode)
           (outline-hide-body)
           (toggle-truncate-lines)
           (org-sidebar-outline-mode)
           (evil-normalize-keymaps)
           ;; Do this twice in case the point is in a hidden line
           (dotimes (_ 2 (forward-line 0)))
           ))
    ))

(defun fab/jump-to-point-and-show ()
  "Switch to a cloned buffer's base buffer and move point to the cursor position in the clone."
  (interactive)
  (let ((buf (buffer-base-buffer)))
    (unless buf
      (error "You need to be in a cloned buffer!"))
    (let ((pos (point))
          (win (car (get-buffer-window-list buf))))
      (if win
          (select-window win)
        (other-window 1)
        (switch-to-buffer buf))
      (goto-char pos)
      (when (invisible-p (point))
        (show-branches)))))

(general-def '(normal visual) org-mode-map
  "<down>" 'evil-next-visual-line
  "<up>"   'evil-previous-visual-line)

(general-def 'normal org-mode-map "C-e" 'org-edit-special)
;; Use minor-mode-define-key to load keys immediatly
(evil-define-minor-mode-key '(normal insert) 'org-src-mode (kbd "C-e") 'org-edit-src-exit)

(fab/leader-def org-mode-map :infix "o"
  ""    '(:ignore t :wk "Org-Mode")
  "g"   '(counsel-org-goto :wk "Goto Counsel")
  "G"   '((lambda () (interactive) (evil-emacs-state) (org-goto) (evil-normal-state)) :wk "Goto Interactive")
  ;; "o"   '(org-occur :wk "Occur")
  "o"   '(fab/open-tree-view :wk "Overview")

  ;; "s"   '(:ignore t :wk "Src Blocks")
  ;; "s s" '((lambda () (interactive) (beginning-of-line) (org-babel-demarcate-block)) :wk "Split or create")

  "t"   '(:ignore t :wk "Tables")
  "t t" '(org-table-create-or-convert-from-region :wk "Create")
  "t c" '(:ignore t :wk "Columns")
  "t c d" '(org-table-delete-column :wk "Delete")
  "t c i" '(org-table-insert-column :wk "Insert Before")
  "t c I" '(org-table-insert-column-after :wk "Insert After")
  "t s" '(org-table-sort-lines :wk "Sort by Column")
  ;; "t d" '(org-table-cut-region :wk "Delete")
  ;; "t y" '(org-table-copy-region :wk "Yank")
  ;; "t p" '(org-table-paste-rectangle :wk "Paste")
  "t i" '(org-table-import :wk "Import")
  "t e" '(org-table-export :wk "Export")

  "m"   '(:ignore t :wk "Modes")
  "m a" '(org-appear-mode :wk "Appear")
  "m f" '(org-fragtog-mode :wk "Latex Fragments")
  "m F" '((lambda () (interactive) (org-fragtog-mode -1) (org-fragtog-mode 1)) :wk "Latex Fragments Restart")
  "m f" '(org-num-mode :wk "Numbers")
  "m e" '(org-toggle-pretty-entities :wk "Entities")
  "m i" '(org-toggle-inline-images :wk "Images")

  "i"   '(:ignore t :wk "Insert")
  "i e" '(counsel-org-entity :wk "Entity")
  "i l" '(org-insert-link :wk "Link")
  "i L" '(counsel-org-link :wk "Link (Headline)")
  "i t" '(org-table-create :wk "Table")
  "i s" '((lambda () (interactive) (beginning-of-line) (org-babel-demarcate-block)) :wk "Source Block (Split)")

  "I"   '(:ignore t :wk "Insert Preset")
  "I d" '((lambda () (interactive) (unless (curr-line-empty-p) (end-of-line) (insert "\n")) (insert "#+OPTIONS: d:nil")) :wk "No-Export Drawer")
  "I t" '((lambda () (interactive) (unless (curr-line-empty-p) (end-of-line) (insert "\n")) (insert "#+OPTIONS: toc:nil")) :wk "No-Export Table of Contents")
  "I n" '((lambda () (interactive) (unless (curr-line-empty-p) (end-of-line) (insert "\n")) (insert "#+STARTUP: num") (org-num-mode 1)) :wk "Enable Numbers")
  "I l"   '(:ignore t :wk "Latex")
  "I l g"
  '((lambda ()
      (interactive)
      (unless (curr-line-empty-p) (end-of-line) (insert "\n"))
      (insert "#+LANGUAGE: de\n")
      (insert "#+LATEX_HEADER: \\usepackage{icomma}\n")
      (insert "#+LATEX_HEADER: \\usepackage{csquotes}\n#+LATEX_HEADER: \\MakeOuterQuote{\"}"))
    :wk "German Setup")
  "I l h" '((lambda () (interactive) (unless (curr-line-empty-p) (end-of-line) (insert "\n"))
      (insert "#+LATEX_HEADER: \\usepackage{hyphenat}\n#+LATEX_HEADER: \\hyphenation{}"))
    :wk "Hypenation")

  "l"   '(org-latex-preview :wk "Latex Preview")

  "T"   '(org-todo :wk "Change TODO")
  "S"   '(org-sort :wk "Sort")
  )

(defun org-folded-p ()
  "Returns non-nil if point is on a folded headline or plain list item."
  (and (or (org-at-heading-p) (org-at-item-p))
       (invisible-p (point-at-eol))))

(defun org-before-item-bullet-p ()
  "Is point at or before the bullet of a plain list item?
Also works for numbered lists."
  (and (org-at-item-p)
       (< (point) (match-end 0))))

(defun fab/org-evil-list-open-item-above (insert)
  (interactive "P")
  (if insert
      (evil-open-above 1)
    (org-evil-list-open-item-above)))

(defun fab/org-evil-list-open-item-below (insert)
  (interactive "P")
  (if insert
      (evil-open-below 1)
    (org-evil-list-open-item-below)))

(defun fab/org-evil-list-insert-item (insert)
  (interactive "P")
  (if insert
      (org-return)
    (when (org-before-item-bullet-p)
      (org-evil-list-beginning-of-item))
    (let ((text (delete-and-extract-region (point) (line-end-position))))
      (org-end-of-item)
      (org-insert-item (org-at-item-checkbox-p))
      (insert text)
      (org-evil-list-beginning-of-item))))

(defun fab/org-evil-heading-open-sibling-below (insert)
  (interactive "P")
  (if (or insert (org-folded-p))
      (org-evil-heading-open-sibling-below)
    (evil-open-below 1)))

(defun fab/org-evil-heading-open-sibling-above (insert)
  (interactive "P")
  (if (or insert (org-folded-p))
      (org-evil-heading-open-sibling-above)
    (evil-open-above 1)))

(evil-define-motion fab/org-evil-heading-beginning-of-line ()
  "Move to the beginning of the current heading."
  :type exclusive
  (org-back-to-heading)
  (re-search-forward "\*+ "))

(use-package org-evil
  :after org
  :load-path "~/.config/emacs/org-evil"
  :config
  (org-evil--define-key 'normal 'org-evil-list-mode
    "O" 'fab/org-evil-list-open-item-above
    "o" 'fab/org-evil-list-open-item-below)
  (org-evil--define-key 'insert 'org-evil-list-mode
    (kbd "RET") 'fab/org-evil-list-insert-item)
  (org-evil--define-key 'normal 'org-evil-heading-mode
    "O" 'fab/org-evil-heading-open-sibling-above
    "o" 'fab/org-evil-heading-open-sibling-below
    "^" 'fab/org-evil-heading-beginning-of-line))

(defun fab/evil-clone-split ()
  (interactive)
  (evil-window-split)
  (switch-to-buffer (clone-indirect-buffer nil nil)))

(defun fab/evil-clone-vsplit ()
  (interactive)
  (evil-window-vsplit)
  (switch-to-buffer (clone-indirect-buffer nil nil)))

(general-def evil-window-map
  "S" 'fab/evil-clone-split
  "V" 'fab/evil-clone-vsplit)

(defun fab/org-prettify-symbols-setup ()
  (setq prettify-symbols-unprettify-at-point 't)
  (push '("[ ]" . ?) prettify-symbols-alist)
  (push '("[X]" . ?) prettify-symbols-alist)
  (prettify-symbols-mode))

(add-hook 'org-mode-hook 'fab/org-prettify-symbols-setup)

(define-abbrev-table 'org-mode-abbrev-table
  '(("->" "\\rightarrow")
    ("=>" "\\Rightarrow")
    ("..." "\\dots"))
  :regexp (rx (or bol (not (any "=" "-" ">" "." wordchar)))
      (group (one-or-more (any "=" "-" ">" "." wordchar)))
      (zero-or-more (not (any "=" "-" ">" "." wordchar)))))

(add-hook 'org-mode-hook 'abbrev-mode)

(general-def 'insert org-mode-map
  "SPC" '(lambda (N) (interactive "p") (unless (org-in-src-block-p) (expand-abbrev)) (org-self-insert-command N)))

(setq org-confirm-babel-evaluate nil)

;; Automatically tangle our Emacs.org config file when we save it
(defun fab/org-auto-tangle ()
  (when (and (eq major-mode 'org-mode)
             (string-equal (file-name-directory (buffer-file-name))
                           (expand-file-name user-emacs-directory)))
    ;; Dynamic scoping to the rescue
    (let ((org-confirm-babel-evaluate nil))
      (org-babel-tangle))))

(add-hook 'org-mode-hook (lambda () (add-hook 'after-save-hook #'fab/org-auto-tangle)))

(setq org-latex-listings t)
(setq org-latex-packages-alist
      '(("AUTO" "babel" t)
        ("" "listings" t)
        ("" "comment" t)
        ("" "xcolor" t)
        ("" "geometry")))

;; Use ppdflatex for nicer outputs, when compiling
(setq org-latex-pdf-process '("latexmk -f -pdf -%latex -pdflatex=\"ppdflatex %%O %%S\" -interaction=nonstopmode -output-directory=%o %f"))

;; Add more files to cleanup
(with-eval-after-load 'ox-latex
  (push "lof" org-latex-logfiles-extensions)
  (push "lot" org-latex-logfiles-extensions))

;; Automatically open PDF File after exporting
(advice-add 'org-latex-export-to-pdf :after
            (lambda (&optional async subtreep visible-only body-only ext-plist)
              (let* ((filename (org-export-output-file-name ".pdf" subtreep))
                     (buffer (or (get-file-buffer filename) (find-file-noselect filename)))
                     (window (get-buffer-window buffer))
                     (split-height-threshold nil)
                     (split-width-threshold 0))
                (cond (window
                       (select-window window))
                      (buffer
                       (switch-to-buffer-other-window buffer))
                      (t
                       (message "Could not open PDF File."))))))

(use-package tree-sitter
  :hook (prog-mode . global-tree-sitter-mode) ;; Turn on parsing by tree sitter
  :config
  (remove-hook 'prog-mode-hook #'global-tree-sitter-mode) ;; Remove hook, to avoid double trigger
  (add-hook 'tree-sitter-after-on-hook #'tree-sitter-hl-mode) ;; Turn on highlighting by tree-sitter
  )

(use-package tree-sitter-langs
  :after tree-sitter)

(use-package lsp-mode
  :commands (lsp lsp-deferred)
  :hook ((lsp-mode . evil-force-normal-state))
  :init
  (setq lsp-keymap-prefix "C-l")
  (setq lsp-headerline-breadcrumb-segments '(path-up-to-project file symbols))
  ;; (setq lsp-signature-auto-activate nil)
  ;; (setq lsp-signature-render-documentation nil)
  (setq lsp-modeline-diagnostics-enable nil) ;; Provided by flycheck
  :config
  (lsp-enable-which-key-integration t)
  (fab/leader-def lsp-mode-map "l" (general-simulate-key "C-l" :which-key "LSP"))
  (general-def 'normal lsp-mode-map
    "C-<return>" 'lsp-find-definition))

(use-package flycheck
  :after lsp-mode) ;; TODO: Configure

(use-package yasnippet
  :hook (lsp-mode . yas-minor-mode)
  :config
  (yas-reload-all))

(use-package yasnippet-snippets
  :after yasnippet)

(use-package lsp-ui
  :after lsp-mode
  :config
  (set-face-attribute 'lsp-ui-peek-header nil :background "#cbbb92" :foreground "#282828")
  :custom
  (lsp-ui-sideline-delay 0)
  (lsp-ui-sideline-show-code-actions nil)

  (lsp-ui-doc-show-with-cursor nil)
  (lsp-ui-doc-position 'at-point)
  (lsp-ui-doc-include-signature 't) ;; TODO: Auswirkung unbekannt
  )

(use-package lsp-ivy
  :after lsp-mode
  :config
  ;; Filter out Fields in Structs
  (setq lsp-ivy-filter-symbol-kind '(8))
  (general-def lsp-command-map
    "j" '(fab/lsp-ivy-workspace-symbol-strict :wk "jump"))
  ;; Describtion needs to be added manually, since LSP Mode is wierd
  (which-key-add-key-based-replacements "C-l j" "jump"))

(defun fab/lsp-ivy--workspace-symbol-action (sym-string)
  "Jump to the `&SymbolInformation' defined in SYM-STRING."
  (lsp-ivy--goto-symbol (get-text-property 0 'lsp-ivy-symbol sym-string))
  (recenter 3))

(defun fab/lsp-ivy-workspace-symbol-update-fn ()
  (when (> (length (ivy-state-current ivy-last)) 0)
    (with-ivy-window
      (fab/lsp-ivy--workspace-symbol-action (ivy-state-current ivy-last)))))

(defun fab/lsp-ivy-workspace-symbol-strict (arg)
  "`ivy' for lsp workspace/symbol.
When called with prefix ARG the default selection will be symbol at point."
  (interactive "P")
  (fab/lsp-ivy--workspace-symbol-strict (lsp-workspaces)
                             "Workspace symbol: "
                             (when arg (thing-at-point 'symbol))))

(defun fab/lsp-ivy--workspace-symbol-strict (workspaces prompt initial-input)
  "Search against WORKSPACES with PROMPT and INITIAL-INPUT."
  (let* ((non-essential t)
         (prev-query nil)
         (unfiltered-candidates '())
         (workspace-root (lsp-workspace-root)))
    (ivy-read
     prompt
     (lambda (user-input)
       (let* ((parts (split-string user-input))
              (query (or (car parts) ""))
              (filter-regexps? (mapcar #'regexp-quote (cdr parts))))
         (unless (string-equal prev-query query)
           (setq unfiltered-candidates
                 (with-lsp-workspaces workspaces
                   (lsp-request-while-no-input
                    "workspace/symbol"
                    (lsp-make-workspace-symbol-params :query query)))))
         (setq prev-query query)
         (--keep (and ;; This here is my custom code
                  (string-prefix-p
                   (concat "file://" workspace-root)
                   ;; (gethash "uri" (gethash "location" it)))
                   (plist-get (plist-get it ':location) ':uri))
                  (lsp-ivy--transform-candidate it filter-regexps? workspace-root))
                 unfiltered-candidates)))
     :dynamic-collection t
     :require-match t
     :initial-input initial-input
     :action #'fab/lsp-ivy--workspace-symbol-action
     :update-fn #'fab/lsp-ivy-workspace-symbol-update-fn
     :caller 'lsp-ivy-workspace-symbol)))

(add-hook 'c-mode-common-hook 'lsp-deferred)

(use-package go-mode
  :mode "\\.go\\'"
  :hook (go-mode . lsp-deferred))

(use-package sh-script
  :hook (sh-mode . lsp-deferred)
  :init
  (setq lsp-bash-explainshell-endpoint "http://localhost:5000"))

(use-package elisp-check
  :load-path "~/.config/emacs/elisp-check"
  :autoload elisp-check-run)

(use-package auctex
  :hook (((LaTeX-mode latex-mode) . lsp-deferred)
         ((LaTeX-mode latex-mode) . TeX-source-correlate-mode))
  :init
  (setq TeX-auto-save t)
  (setq TeX-parse-self t)
  (setq-default TeX-master nil))

(use-package company-auctex
  :after (auctex company)
  :config
  (company-auctex-init))

(use-package reftex
  ;; :hook ((latex-mode LaTeX-mode) . reftex-mode)
  :after auctex
  :init
  (setq reftex-plug-into-AUCTeX t)
  :config
  (add-hook 'LaTeX-mode-hook 'turn-on-reftex) ;; with AUCTeX LaTeX mode
  (add-hook 'latex-mode-hook 'turn-on-reftex) ;; with Emacs latex mode
  )

(add-hook 'latex-mode-hook 'toggle-word-wrap)
(add-hook 'LaTeX-mode-hook 'toggle-word-wrap)

(defun fab/latex-prettify-symbols-setup ()
  (setq prettify-symbols-unprettify-at-point 't)
  (push '("\\hyph{}" . ?-) prettify-symbols-alist)
  (prettify-symbols-mode))

(add-hook 'latex-mode-hook 'fab/latex-prettify-symbols-setup)
(add-hook 'LaTeX-mode-hook 'fab/latex-prettify-symbols-setup)

(use-package pdf-tools
  :init
  (pdf-loader-install)
  (setq TeX-view-program-selection '((output-pdf "PDF Tools")))
  :magic ("%PDF" . pdf-view-mode)
  :config
  (add-hook 'TeX-after-compilation-finished-functions #'TeX-revert-document-buffer)
  (add-hook 'pdf-view-mode-hook (lambda () (setq cursor-in-non-selected-windows nil)))
  (add-hook 'pdf-view-mode-hook #'pdf-view-auto-slice-minor-mode))

(use-package jupyter
  :after org
  :custom
  (org-babel-load-languages (append org-babel-load-languages '((jupyter . t))))
  :config
  (setq jupyter-repl-echo-eval-p 't)
  (setq jupyter-eval-use-overlays 't)
  (setq org-babel-jupyter-resource-directory (no-littering-expand-var-file-name "ob-jupyter/"))

  (add-to-list 'org-structure-template-alist '("jpy" . "src jupyter-python"))
  (setq org-babel-default-header-args:jupyter-python '((:kernel . "python3")
                                                       (:session . "org-py")
                                                       ;; (:pandoc . t)
                                                       ))
  (advice-add 'org-babel-execute-src-block :after
              (lambda (&rest r) (org-redisplay-inline-images)))

  ;; Redifine function, since ansi-color--find-face has been renamed and apply-on-region has new functionality
  ;; MAY BREAK in Future!
  (defun jupyter-ansi-color-apply-on-region (begin end)
    (ansi-color-apply-on-region begin end t))
  )
