#!/usr/bin/env bash

# Simple univarsal bookmark utility

BFILE=~/.config/bookmarks

if [[ $# -lt 1 ]]; then
    echo "No command provided." 1>&2
    exit 1
fi

cmd=$1

BM="$(sed '/^$/d' "$BFILE")"

case "$cmd" in
    "gen-bash")
        printf "alias b%s='cd %s'\n" $BM
        ;;
    "gen-lf")
        printf "map b%s cd %s\n" $BM
        ;;
    "edit")
        $EDITOR $BFILE
        ;;
    "fzf")
        echo "$BM" | fzf --header='Bookmarks:' --preview='exa -aFT -L1 --icons --group-directories-first --color=always $(echo {} | cut -f 2 -d " " | sed "s|~|$HOME|")' --keep-right | cut -f 2 -d " " | sed "s|~|$HOME|"
        ;;
    *)
        echo "Unknown command!" 1>&2
        exit 1
esac

