#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

if [[ ! -v DOT_DIR ]] && ! DOT_DIR="$(git -C "$(dirname $0)" rev-parse --show-toplevel)"; then
    echo "Could not find git directory to operate from." 1>&2
    echo "Set directory with DOT_DIR." 1>&2
    exit 1
fi

if [[ ! -d "$DOT_DIR" ]]; then
    echo "DOT_DIR is not a valid directory." 1>&2
    echo "DOT_DIR=$DOT_DIR" 1>&2
    exit 1
fi

# === STOW ===

STOW_DIR="$DOT_DIR"
STOW_DEFAULT_PACKAGES=(base private unused)

# Calls stow to update all symlinks in HOME.
# Arguments can be used to specify packages, otherwise use default packages.
function dot-restow () {
    packages=( ${STOW_DEFAULT_PACKAGES[@]} )
    if [[ $# -gt 0 ]]; then
        packages=( "$@" )
    fi

    # Construct command array manually, to avoid issues with word splitting with IFS
    args=()
    for p in "${packages[@]}"; do
        args=(${args[@]} -R "$p")
    done

    stow -d "$STOW_DIR" -t "$HOME" ${args[@]}
}

function adopt-into () {
    # TODO: This currently fails if run from inside the dotfiles directory.
    echo "Currently unsupported!" 1>&2
    return 1
    # TODO: Automatically add new files to git repo?
    if [[ $# -lt 2 ]]; then
        echo "Usage: dot adopt PACKAGE FILES"
        exit 1
    fi
    package="$1"
    shift
    filepaths=( $(realpath --no-symlinks -e --relative-to=$HOME $@) )
    reldirs=( $(dirname ${filepaths[@]}) )

    # Make sure paths exist in STOW_DIR
    for rd in "${reldirs[@]}"; do
        mkdir -pv "$STOW_DIR/$package/$rd"
    done

    # Move all files over into STOW_DIR
    for f in "${filepaths[@]}"; do
        mv -v -i -T "$HOME/$f" "$STOW_DIR/$package/$f"
    done

    dot-restow "$package"
}



# === NIX ===

NIXOS_DIR="$DOT_DIR/nixos"

function dot-nixos () {
	# TODO: Don't use cd. It can have unexpected side effects if things happen after this function.
    cd "$NIXOS_DIR"

    # TODO: Use ** expression. (Needs an option enabled?)
    nix fmt *.nix */*.nix
    nix flake update
    git add .

    if [[ $(type -P nh) ]]; then
        nh os switch . -- "$@"
    else
        nixos-rebuild switch --use-remote-sudo --flake . "$@"
    fi
}



# === MAIN ===

function dot-help () {
    echo "Available commands:"
    echo "stow [PACKAGES] - Rerun stow with provided [PACKAGES] or use default: ${STOW_DEFAULT_PACKAGES[@]}"
    echo "adopt PACKAGE FILES - Move [FILES] into stow [PACKAGE]."
    echo "nixos [ARGS] - Rebuild NixOS"
    exit 1
}

[[ $# -eq 0 ]] && (exec 1>&2; echo "No command provided." ; dot-help)

CMD="$1"
shift

case "$CMD" in
    stow)
        dot-restow "$@";;
    adopt)
        adopt-into "$@";;
    nixos)
        dot-nixos "$@";;
    *)
        exec 1>&2
        echo "Command not recognized."
        dot-help;;
esac

