#!/bin/sh

# This script enables the second Monitor, if it is plugged in, or disables it, if not.
# If $1 is set to --nobg it doesn't update background.

PRIMARY="eDP-1"
MONITOR="HDMI-1"

function getDimensions () {
    xrandr | grep "^$1 connected" -A 1 | tail -n 1 | awk '{print $1}'
}

function getWidth () {
    getDimensions "$1" | cut -d "x" -f 1
}

function getHeight () {
    getDimensions "$1" | cut -d "x" -f 2
}

if xrandr | grep -q "^$MONITOR connected"; then
    PH=$(getHeight $PRIMARY)
	MH=$(getHeight $MONITOR)
	MW=$(getWidth $MONITOR)
    # Setup positions manually, to align bottom edges
	xrandr --output $MONITOR --auto --pos 0x0 \
        --output $PRIMARY --auto --pos ${MW}x$(( $MH - $PH ))
elif xrandr | grep -q "^$MONITOR disconnected"; then
	xrandr --output $PRIMARY --auto \
        --output $MONITOR --off
fi

[ "$1" = "--nobg" ] || (sleep 1; setbg)

exit 0

