#!/usr/bin/env bash

max=256
if [ "$1" = "-16" ]; then
    max=16
elif [ "$1" = "-8" ]; then
    max=8
fi

i=0
while [ "$i" -lt "$max" ] ; do

    printf "\e[48;5;%sm%3d\e[0m " "$i" "$i"
    m=$(( ($i - 15) % 6 ))
    if [[ $i -eq 7 || $i -eq 15 || $i -eq 243 || ( $i -gt 15 && $i -lt 232 && $m -eq 0 ) ]]; then
        printf "\n";
    fi
    m=$(( ($i - 15) % 36 ))
    if [[ $i -eq 15 || $i -eq 255 || ($i -gt 15 && $m -eq 0 ) ]]; then
        printf "\n";
    fi

    i=$(($i + 1))
done
