#!/bin/sh

#  _____             __     __             
# | ____|_ ____   __ \ \   / /_ _ _ __ ___ 
# |  _| | '_ \ \ / /  \ \ / / _` | '__/ __|
# | |___| | | \ V /    \ V / (_| | |  \__ \
# |_____|_| |_|\_/      \_/ \__,_|_|  |___/

# In this file all Shell and Enviroment Variables are set up.
# Source this in your Shell profile or rc File.

# A Helper function, to test if a programm can be run (is installed)
# (Overwrites the script, to include aliases etc.)
function isInstalled(){
	which "$1" 1&>/dev/null
}

# === Setup PATH ===
# (avoids dublications)
[[ $PATH =~ $HOME/bin ]] || PATH="$HOME/bin:$PATH"
[[ $PATH =~ $HOME/.local/bin ]] || PATH="$HOME/.local/bin:$PATH"
[[ $PATH =~ $HOME/scripts ]] || PATH="$HOME/scripts:$PATH"

# === Config some programms ===

# LS Colors and LF Icons
eval "$(dircolors -b ~/.config/bash/.dircolors)"
isInstalled "lf" && source ~/.config/lf/lficons.sh

# Add Color Support for less and ignore case
export LESS="-R -I --mouse"

# Setup FZF
if isInstalled "fzf"; then
	export FZF_DEFAULT_OPTS="--info=inline --reverse --cycle \
	--prompt='❯ ' --pointer='❯' --marker='❯' \
	--color=16,border:8,gutter:-1,spinner:1,prompt:2,pointer:4,header:3,fg+:7,bg+:238 --ansi \
	--bind 'change:top,ctrl-d:half-page-down,ctrl-u:half-page-up,alt-enter:replace-query,alt-p:toggle-preview,alt-s:toggle-sort,ctrl-k:clear-query,ctrl-g:top'"
fi

# Remove Members from ctags output, to avoid false positives
isInstalled "ctags" && export CTAGS="--kinds-C=-m"

# === Setup Default applications ===

# Use NeoVim if available
if isInstalled "nvim"; then
	export EDITOR="nvim"
else
	export EDITOR="vim"
	export VISUAL="gvim"
fi
export PAGER="less"
# export BROWSER="surf"
export BROWSER="firefox"

if isInstalled "st"; then
	export TERMINAL="st"
fi

# === Change config file locations ===

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_DATA_DIRS="/usr/local/share:/usr/share"
export XDG_CONFIG_DIRS="/etc/xdg"

export XAUTHORITY="$XDG_CACHE_HOME/Xauthority"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export IPYTHONDIR="$XDG_CONFIG_HOME/jupyter"
export JUPYTER_CONFIG_DIR="$XDG_CONFIG_HOME/jupyter"
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME/java"
export MPLAYER_HOME="$XDG_CONFIG_HOME/mplayer"
export GOPATH="$XDG_DATA_HOME/go"
export NODE_REPL_HISTORY="$XDG_DATA_HOME/node_repl_history"
export KDEHOME="$XDG_CONFIG_HOME/kde"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export PYLINTHOME="$XDG_CACHE_HOME/pylint"
export TERMINFO="$XDG_DATA_HOME/terminfo"
export TERMINFO_DIRS="$XDG_DATA_HOME/terminfo:/usr/share/terminfo"
export TEXMFHOME="$XDG_DATA_HOME/texmf"
export TEXMFVAR="$XDG_CACHE_HOME/texlive/texmf-var"
export TEXMFCONFIG="$XDG_CONFIG_HOME/texlive/texmf-config"
export WORKON_HOME="$XDG_DATA_HOME/virtualenvs"

# Might break
export VSCODE_PORTABLE="$XDG_CONFIG_HOME/vscode"
export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc.py"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"

export LESSHISTFILE="-" # Remove Less History File

