#!/bin/sh

# Default Profile File. Source this file in your Shell Profile file.

# Start X Server, when TTY is 1 (the default one after boot) and we are in a login shell (so no shell that is run via command.)
if [ "$(tty)" = "/dev/tty1" ]; then

	neofetch

	printf "Start X Session? [Y/n]"
	read ans
	if [ -z "$ans" ]; then
		echo "" > ~/.cache/reload_selection.cache
		~/scripts/xloop.sh
		[ "$(cat ~/.cache/reload_selection.cache)" = "logout" ] && logout
	fi
fi

