_M = {{
    background = '{background}',
    foreground = '{foreground}',
    cursor = '{cursor}',
    black = '{color0}',
    red = '{color1}',
    green = '{color2}',
    yellow = '{color3}',
    blue = '{color4}',
    magenta = '{color5}',
    cyan = '{color6}',
    brightgray = '{color7}',
    darkgray = '{color8}',
    brightred = '{color9}',
    brightgreen = '{color10}',
    brightyellow = '{color11}',
    brightblue = '{color12}',
    brightmagenta = '{color13}',
    brightcyan = '{color14}',
    brightwhite = '{color15}',
    color0 = '{color0}',
    color1 = '{color1}',
    color2 = '{color2}',
    color3 = '{color3}',
    color4 = '{color4}',
    color5 = '{color5}',
    color6 = '{color6}',
    color7 = '{color7}',
    color8 = '{color8}',
    color9 = '{color9}',
    color10 = '{color10}',
    color11 = '{color11}',
    color12 = '{color12}',
    color13 = '{color13}',
    color14 = '{color14}',
    color15 = '{color15}',
}}

return _M

