#!/bin/sh

TMPFILE=~/.cache/bspwm/swallowids

# Get class of a wid
get_class() {
	id=$1
	if [ -z "$id" ]; then
		echo ""
	else
		xprop -id "$id" | sed -n '/WM_CLASS\|WM_COMMAND/s/.*"\(.*\)".*/\1/p'
	fi
}

get_pid() {
	[ -z "$1" ] && return
	# List always all Atoms, in case PID is not supported by window
	xprop -id "$1" | grep "_NET_WM_PID" | sed 's/.* = //'
}

swallow() {
	addedtodesktop=$2
	lasttermdesktop=$(bspc query -D -n last)

	swallowerid=$1
	swallowingid=$(bspc query -N -n last)

	if [ "$addedtodesktop" = "$lasttermdesktop" ]; then
		cat ~/.config/bspwm/noswallow ~/.config/bspwm/terminals | grep -q "^$(get_class "$swallowerid")$" && return
		grep -q "^$(get_class "$swallowingid")$" ~/.config/bspwm/terminals || return
		swallowerpid="$(get_pid $swallowerid)"
		[ -z "$swallowerpid" ] && return
		swallowingpid="$(get_pid $swallowingid)"
		[ -z "$swallowingpid" ] && return
		listancestors "$swallowerpid" | grep -q "^$swallowingpid$" || return
		echo "$swallowerid $swallowingid" >> $TMPFILE
		bspc node "$swallowingid" --flag hidden=on
	fi
}

spit() {
	spitterid=$1
	spitterdesktop=$2
	grep -q "^$spitterid" $TMPFILE || return
	spittingid=$(grep "^$spitterid" $TMPFILE | head -n1 | awk '{print $2}')

	bspc node "$spittingid" --flag hidden=off

	termdesktop=$(bspc query -D -n "$spittingid")
	[ "$termdesktop" = "$spitterdesktop" ] || bspc node "$spittingid" -d "$spitterdesktop"

	bspc node "$spittingid" -f
	sed -i "/^$spitterid/d" $TMPFILE
}

bspc subscribe node_add node_remove | while read -r event
do
	case $(echo "$event" | awk '{ print $1 }') in
		node_add)
            		swallow $(echo "$event" | awk '{print $5 " " $3}')
			;;
		node_remove)
			spit $(echo "$event" | awk '{print $4 " " $3}')
			;;
	esac
done
