#!/bin/sh

# Sends a node to a preselection, if one is available,
# otherwise a receptacle, otherwise a marked one,
# lastly the biggest one.
# If $1 is --swap, it swaps instead.
# Only sends / swaps to a local node

if [ "$1" == "--swap" ]; then
	OPTION="--swap"
else
	OPTION="--to-node"
fi

# Preselection
NODE="$(bspc query -N -n biggest.!automatic.window.local.\!focused)"
if [ "$?" -eq 0 ]; then
	bspc node $OPTION "$NODE"
	bspc node -f
	exit 0
fi

# Receptacle
NODE="$(bspc query -N -n biggest.!window.leaf.local)"
if [ "$?" -eq 0 ]; then
	bspc node $OPTION "$NODE"
	bspc node -f
	exit 0
fi

# Marked
NODE="$(bspc query -N -n biggest.marked.local.\!focused)"
if [ "$?" -eq 0 ]; then
	bspc node $OPTION "$NODE"
	bspc node -f
	exit 0
fi

# Biggest
NODE="$(bspc query -N -n biggest.leaf.local.\!focused)"
if [ "$?" -eq 0 ]; then
	bspc node $OPTION "$NODE"
	bspc node -f
	exit 0
fi

