#!/bin/sh

TERMNAME="st-256color"

bspc query -N -n .window | while read WID; do
	if (xprop -id "$WID" WM_CLASS | grep -q "$TERMNAME"); then
		xprop -id "$WID" _NET_WM_PID | sed 's/_NET_WM_PID(CARDINAL) = //'
	fi
done

