#!/bin/sh

# This script enables the second Monitor, if it is plugged in, or disables it, if not.

PRIMARY="eDP1"
MONITOR="HDMI1"
MAINMODE="1366x768"

if xrandr | grep -q "^$MONITOR connected"; then
	xrandr --output $PRIMARY --pos 0x0 --mode $MAINMODE
	xrandr --addmode $MONITOR $MAINMODE
	xrandr --output $MONITOR --same-as $PRIMARY --mode $MAINMODE
elif xrandr | grep -q "^$MONITOR disconnected"; then
	xrandr --output $MONITOR --off
fi

setbg

case "$(getcurrwm)" in
	"bspwm")
		# TODO: Move in BSPWMRC as extra Script
		bspwm_monitor_setup;;
esac

