#!/bin/sh

# A Simple Script, that opens DMenu with a simple Yes / No choise.
# It exits 0 if Yes was selected and 1 if No was selected.

# $1 is a Prompt Text.
# After that a range of option can be supplied.

[[ $@ == *'-TF'* ]] && OPT="True\nFalse"
[[ $@ == *'-FT'* ]] && OPT="False\nTrue"
[[ $@ == *'-NY'* ]] && OPT="No\nYes"
[[ $@ == *'-YN'* ]] || [ -z "$OPT" ] && OPT="Yes\nNo"

SEL=$(printf "$OPT" | dmenu -p "$1" -l 2 -i)

# Exit succesfully, only when Yes (or True) was selected
[ "$SEL" = "Yes" ] || [ "$SEL" = "True" ] && exit 0

# On anything else, fail.
exit 1
