#!/bin/sh

# This script generates a status bar
# At the Moment it is piped directly to xsetroot, to set the status for dwm.

STARTSTR=''
SEPERATOR='  '
FIFO=~/.cache/status_bar_fifo

# Setup Vars and FIFO
set -a STATUS

rm -f $FIFO
mkfifo $FIFO

xsetroot -name ""

# Now update status bar every Time new Input comes
while true; do
	# Work through every new input line. (When more than one line comes at a time. E.g. at Startup)
	while read OUT; do
		# Get and set Text
		INDEX=$(echo "$OUT" | cut -f1)
		TEXT=$(echo "$OUT" | cut -s -f2)
		STATUS[$INDEX]="$TEXT"

		# Construct String
		STRING=""
		for S in "${STATUS[@]}"; do
			if [ "$S" ]; then
				STRING="${STRING}${SEPERATOR}${S}"
			fi
		done

		# Remove Initial Seperator
		STRING=$(echo "$STRING" | sed "s/^$SEPERATOR//")
		# Append Leading and Trailing Spaces and StartStr
		STRING="$STARTSTR $STRING "
		xsetroot -name "$STRING"
	done < $FIFO
done

rm $FIFO

