#!/bin/sh

BATTERY_NAME='BAT1'

dwm_status_bar_volume &

while true; do
	TIME=$(date +"%-S")
	TIME=$(( $TIME % 2 ))
	if [ "$TIME" -eq 0 ]; then
		TIME=$(date +"%-H:%M")
	else
		TIME=$(date +"%-H %M")
	fi

	dwm_status_bar_send 1 "$TIME"
	
	POWER=" $(cat /sys/class/power_supply/$BATTERY_NAME/capacity)%"
	dwm_status_bar_send 2 "$POWER"

	sleep 1
done

