#!/bin/sh

# This script allows the user to search and select a file via fzf and then opens this file in an editor for further inspection / editing.
# If the first argument is "--stay" the script will not change the Working Directory to the file.

# Filter out git and cache Directories and log files as well as binary files (via the grep)
FILE=$(fastfind . 2>/dev/null \
     | fzf --header-lines=1 --keep-right --multi --cycle --tiebreak=length,end \
           --preview="~/scripts/previewer.sh {}" \
	   --header '= Alt+Enter: Enter Dir; Alt+H: Go to Start =' \
           --bind 'alt-enter:reload(fastfind {})+clear-query+top,alt-h:reload(fastfind .)+clear-query+top' "$@")

[ -z "$FILE" ] && exit 1

if [ "$1" = "--stay" ] || [ "$1" = "-s" ]; then
    exec $EDITOR $FILE
else
    # Switch working directory to file
    cd $(dirname $FILE)
    exec $EDITOR $(basename $FILE)
fi

