#!/bin/sh

# Runs an optimized find command, to exclude common unwanted directories and binary files.
# If the first argument is a file, the directory of the file is instead used.

if [ "$#" = 0 ]; then
	DIR="."
elif [ -d "$1" ]; then
	DIR="$1"
elif [ -f "$1" ]; then
	DIR="$(dirname "$1")"
else
	echo "Could not find path." 1>&2
	exit 1
fi

# Print out the Directory in Full
printf "\033[1;33m $(pwd)\033[0m"
if [ "$DIR" != "." ]; then
	echo "$DIR:" | sed 's/\.//'
else
	echo ":"
fi

# Start Search in Current (earlier changed) dir.
bfs_find "$DIR" \
       -type d \( -name '*.git' -o -iname '*cache*' -o -name 'anaconda*' -o -iname '*trash*' -o -path './Uni/04_SS_20/OS/Projekt/Research' \) -prune \
    -o -type f \( -iname '*log*' \) \
    -o -type f -print0 \
    | xargs -0 grep -I -D skip -d skip -l "."

