#!/bin/bash

SYNC=""
if [ "$1" = "--sync" ]; then
    SYNC="--sync"
    shift 1
fi

QPATTERN=""
if [ "$#" -eq 0 ]; then
    QPATTERN="--query="
else
    QPATTERN="--query=$1"
    shift 1
fi

if [ "$#" -ne 0 ]; then
    # File List supplied -> search all files
    grep -Hn --color=always "" /dev/null "$@" 2>/dev/null | fzf --no-sort --multi $SYNC --exact "$QPATTERN"
else
    if [ -t 0 ]; then
        # Input is TTY -> Run cat
        cat | fzf --no-sort --multi --sync --exact "$QPATTERN"
    else
        # Input is not TTY -> get input and don't wait for input to finish (unless sync is given)
        exec fzf --no-sort --multi $SYNC --exact "$QPATTERN"
    fi
fi

