#!/bin/sh

ICON="~/.local/share/icons/youtube-icon.png"

# TITLE="$(firefoxGetUrl)"

ACTIVELIST="$(bt list | grep "$(bt active | head -n 1 | awk '{print $1}')")"
URL="$(echo "${ACTIVELIST}" | awk -F '\t' '{print $3}')"
TITLE="$(echo "${ACTIVELIST}" | awk -F '\t' '{print $2}')"

if [ "$URL" ]; then
	notify-send "Youtube-DL" "Start Download of:\n\"$TITLE\"\n($URL)" -i "$ICON"
    youtube-dl "$URL"
    if [ $? -eq 0 ]; then
	    notify-send "Youtube-DL" "Download finished\n\"$TITLE\"" -i "$ICON"
    else
	    notify-send "Youtube-DL Error" "Error downloading video:\n\"$TITLE\"" -u critical -i "$ICON"
    fi
else
    notify-send "Youtube-DL Error" "Could not find URL" -i "$ICON" -u critical
fi
