#!/bin/sh

# Get the number of the first line of stdin, that matches $1.
# Use $2 to set starting integer

ARG="$1"
I="$2"
if [ -z "$I" ]; then
	I=0
fi

while read LINE; do
	if [ "$LINE" = "$ARG" ]; then
		echo "$I"
		exit 0
	fi

	I=$(($I + 1))
done

exit 1

