#!/bin/sh

# This script allows the user to select a file in lf. 
# The selected file is then printed to stdout.

tmp="$(mktemp)"
lf -selection-path="$tmp"

if [ -f "$tmp" ]; then
    file="$(cat "$tmp")"
    rm -f "$tmp"
    
    if [ -f "$file" ]; then
        echo "$file"
        exit 0
    else
        exit 1
    fi

else
    exit 1
fi
