#!/bin/sh

# This script sets the BG and updates the Color Schemes.
# Supply it with a File and it uses this file as a BG, otherwise it will just use the last one.

# Update Cache file, if File is given.
if [ "$1" ]; then
    if [ ! -f "$1" ]; then
        echo "File does not exist."
        exit 1
    fi

    # Differentiating between absolute and relative path
    if [ "${1:0:1}" = "/" ]; then
        echo "$1" > ~/.cache/background
    else
        echo "$(pwd)/$1" > ~/.cache/background
    fi
fi

IMAGE=$(cat ~/.cache/background)

if [ -z "$IMAGE" ] || [ ! -f "$IMAGE" ]; then
    echo "No Image supplied."
    exit 1
fi

echo "Set Wallpaper"
xwallpaper --zoom "$IMAGE" &


echo "Generate Color Scheme"
wal -i "$IMAGE" -stne -q

XRDB_ALPHA="90" # Alpha value for the colors. (Range: 00-ff)
grep '^\*color' ~/.cache/wal/colors.Xresources | sed 's/^\*color\(.*\):\s*\#\(.*\)/alpha_color\1: #'"$XRDB_ALPHA"'\2/' >> ~/.cache/wal/colors.Xresources
xrdb ~/.cache/wal/colors.Xresources


echo "Upadate Color Schemes"
case "$(getcurrwm)" in
	"dwm")
		~/.config/polybar/launch.sh &
		dwmc xrdb &
		;;
	"bspwm")
		~/.config/polybar/launch.sh &

		bspc config normal_border_color $(xrdb -query | grep '^\*color2:' | sed 's/.*\(\#.*\)/\1/')
		bspc config active_border_color $(xrdb -query | grep '^\*color2:' | sed 's/.*\(\#.*\)/\1/')
		bspc config focused_border_color $(xrdb -query | grep '^\*color4:' | sed 's/.*\(\#.*\)/\1/')
		bspc config presel_feedback_color $(xrdb -query | grep '^\*color6:' | sed 's/.*\(\#.*\)/\1/')
		;;
esac

# Restarting Compton causes to much window flickering
# ~/scripts/compton_launch.sh &

