#!/bin/sh

# This script enables the second Monitor, if it is plugged in, or disables it, if not.
# If $1 is set to --nobg it doesn't update background.

PRIMARY="eDP1"
MONITOR="HDMI1"

function getHeight () {
	xrandr | grep "^$1 connected" | sed 's/.* connected\( primary\)\? [0-9]*x\([0-9]*\)+.*/\2/'
}

P_SIZE=$(getHeight $PRIMARY)

if xrandr | grep -q "^$MONITOR connected"; then
	xrandr --output $MONITOR --auto --right-of $PRIMARY
	S_SIZE=$(getHeight $MONITOR)
	xrandr --output $PRIMARY --auto --pos 0x$(( $S_SIZE - $P_SIZE ))
elif xrandr | grep -q "^$MONITOR disconnected"; then
	xrandr --output $MONITOR --off
fi

[ "$1" = "--nobg" ] || setbg

# Run Post Hooks
case "$(getcurrwm)" in
	"bspwm")
		# TODO: Move in BSPWMRC as extra Script
		bspwm_monitor_setup;;
esac

