#!/bin/sh

echo -n "+" >> ~/.cache/time_spent

for i in {1..10}; do
	sleep 60
	pidof firefox telegram-desktop discord && ( notify-send -u critical "BAD PROGRAMM FOUND"; echo -n "-" >> ~/.cache/time_spent )
done

notify-send -u low "10 Minutes done." "Were you productive?"

