#!/bin/bash

# Runs UP and executes command afterwards.

tmp="$(mktemp)"
input="$(mktemp)"

# Copy input and run up
tee "$input" | up -o "$tmp" 2>/dev/null

# Remove the first shebang line, and trailing newlines
cmd="$(tail -n +2 "$tmp" | tr -d "\n")"
rm -f "$tmp"

eval "$cmd" < "$input"
rm -f "$input"

