#!/bin/sh
# Displays the Webcam.

# Run the mplayer in a way, that we can launch it in the background.
# echo "mplayer tv:// -tv driver=v4l2:device=/dev/video0 1&>/dev/null" | sh
ffplay -f video4linux2 -i /dev/video0 -video_size 320x240 &>/dev/null

