#!/bin/sh

FIFO=~/.config/xob/xobfifo

if ! pidof xob &>/dev/null; then
	echo "Xob not started" 1>&2
	exit 1
elif ! [ -p "$FIFO" ]; then
	echo "Could not find FIFO." 1>&2
	exit 1
fi

echo "$1" > "$FIFO"

